# docker-compose.yml
version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - TEMP_DOWNLOAD_DIR=/app/tmp
      - MAX_UPLOAD=500
      - MAXSOLICITUD=2
